[PHP]
max_execution_time = 300
memory_limit = 512M

[xdebug]
xdebug.mode = debug
xdebug.start_with_request = trigger
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003

[opcache]
opcache.enable = 0; # DISABLED FOR DEV
opcache.max_accelerated_files = 20000
opcache.jit = tracing
opcache.jit_buffer_size = 128M
